### ISSUE TITLE
Can’t find global settings in property inspector .html

### ISSUE THREAD

**Issue by dBeau** [gri-gus/streamdeck-python-sdk#1]
Thanks much for all the hard work.  

I’m a Python guy with very little JavaScript experience trying to figure out the JavaScript side of writing a plug-in.  The lorumflickr example was a great help, but it doesn’t show any global settings usage.  I’m pretty sure I’m setting them properly on the Python side, the values show up in the events in the log. But, I can’t figure out how to access them from the JavaScript in property inspector .html.

Care to point me in the right direction?

**Comment by dBeau** [comment]
It's funny how all it takes is asking for the answer to show itself...

I gave my head one more good scratching and here's what I came up with.

```
    let global_settings;
     
    $PI.onDidReceiveGlobalSettings(jsn => {
        console.log('Property Inspector global settings', jsn);

        global_settings = jsn.payload.settings;

        if (global_settings?.some_global) {
            some_global_el.value = global_settings.some_global;
        }
    });

```

**Comment by gri-gus** [comment]
@dBeau You understood everything correctly about the global settings in the Property Inspector. However, do not forget that global settings are not automatically transferred when the Property Inspector is launched, so they must be requested in the `$PI.onConnected` function via `$PI.getGlobalSettings()`. After calling this function, the global settings will get into the `$PI.onDidReceiveGlobalSettings` function.

Example:
```javascript
let settings
let global_settings

$PI.onConnected(jsn => {
    console.log('Property Inspector connected', jsn);
    console.log(jsn.actionInfo.payload.settings);

    settings = jsn.actionInfo.payload.settings;
    
    $PI.getGlobalSettings();
});

$PI.onDidReceiveGlobalSettings(jsn => {
    global_settings = jsn.payload.settings;
});
```

**Comment by dBeau** [comment]
Agree... putting the getGlobalSettings() call in onConnected() first was a big part of the picture.  Your example code really helped a lot too.  

If you have an example that integrates with asyncio, I'd love to see that.  My plug-in needs an event loop of its own.  A minor modification to sdk's StreamDeck.run() has me going with rel for now.  I added a 'dispatcher' parameter to pass to WebSocket's run_forever() method.  

I'm not complaining though... I have a working plug-in now that wouldnt exist if not for your efforts.

**Comment by gri-gus** [comment]
@dBeau Please open a new issue with a question about the event loop and provide an example code.  It will also be good if you describe the task in order to understand exactly how the event loop and the plugin will interact.  I will try to help you and possibly change the library code so that tasks like yours are easier to solve.

**Comment by gri-gus** [comment]
The question required more examples. They have been provided.
