### ISSUE TITLE
How to set_title from function?

### ISSUE THREAD

**Issue by doabigcheese** [gri-gus/streamdeck-python-sdk#6]
Hi,
currently i am stuck on set_title(). Would be nice if someone could assist :)
Goal is to do some Information output (a word) on a dedicated Button, aka change the title.
In my plugin there is some calculation ongoing in a thread function and i want to change a button during the calculation.

```
def myfunction():

   myClassName.set_title(
                   context=obj.context,
                   payload=events_sent_objs.SetTitlePayload(
                       title="111",
                       target=0,
                   )
               )
```

any hint how to achieve this?

**Comment by gri-gus** [comment]
@doabigcheese Hello. Your function with calculations should work in parallel and monitor something, or is it called at the moment the button is pressed/released?

**Comment by doabigcheese** [comment]
@gri-gus  The function is already running in a loop.
so from time to time, i would like to update one specific "output" streamdeck button with information.
In Addition i would also like to change states from one kind of button (but all instances of it (the user can set multiple buttons of one kind but configuration values are different)) at the same time...
so i need to figure out, how to adress those other buttons as well...

**Comment by doabigcheese** [comment]
After reading through the documentation of elgato:
`Events can provide the coordinates of the key on the canvas. With those coordinates, groups of keys can have additional functionality.`
Maybe this is the way to do it? somehow get the coordinate where the "output key" is located and then adress this coordinate directly?
I can save the context-ID at willAppear event, but i have no clue about the syntax to adress the button with this context-ID later :(

**Comment by doabigcheese** [comment]
small finding: if i add a second instance of the output button, and i press the first output button with having a keyup event to set the title, then it will set automaticly both buttons...
but i am not able to achieve the title update from outside the class... so i wonder where the problem is... maybe the "self" ?
what is working (for reference):
```
class myClass(Action):
    UUID = "com.doabigcheese.myplugin.myclass"
    def on_key_up(self, obj: events_received_objs.KeyUp):

        self.set_title(obj.context,
                events_sent_objs.SetTitlePayload(
                    title="111",
                    target=0
                )
            )
```

so hope this is also possible to do from outside the class? so from a function within the main.py (where also this class is defined)

**Comment by doabigcheese** [comment]
what i also tried is to send messages directly with my function:
```
def myfunction():
global my_button_context #set before
(...)
                message = json.dumps({"event": "setTitle",
                                        "context": my_button_context,
                                        "payload": {
                                            "title": "Test Title",
                                            "target": 0
                                        }
                                    })
                
                StreamDeck.ws.send(data=message)
```
But also not working.... -.- 
So question would be: how to send directly a message? maybe you can add some generic "send" method to the SDK?
or give an advice how i can do so :)

**Comment by doabigcheese** [comment]
maybe one remark, as i have the feeling it could be the root cause: 
i have "myfunction()" running in a Thread... so not in the main loop...

**Comment by doabigcheese** [comment]
ok, solved it :)
In my Action Class i assigne a global variable
```
global mother
mother = self
```
And in my thread function i access also this object.
```
def myfucntion():
   global mother
   my_message = json.dumps({"event": "setTitle",
                                        "context": my_button_context,
                                        "payload": {
                                            "title":"Test Title",
                                            "target": 0,
                                        }
                                    })
   mother.ws.send(my_message)
```

**Comment by gri-gus** [comment]
@doabigcheese Hello.  Sorry for the long answer, I can help you tomorrow.  In general, I understood the problem.  You are not using the library correctly, but it's more my fault that the documentation is missing.  Tomorrow I will tell you how to do it right.

**Comment by doabigcheese** [comment]
no worries, if there is a smarter way would be also nice :) but for further developing my plugin i am at least unblocked currently :)

**Comment by doabigcheese** [comment]
@gri-gus Hi again, my next challenge/problem is now: 
how to populate a drop down selection list in the property_inspector html from a button with data from the plugin.
Maybe you could use both usecases from me as a first Tutorial/Example how to do so ?
Tried it with
```
json.dumps({"event": "sendToPropertyInspector",
                    "context": pi_context,
                    "payload": { saved_payload
                    }
                })
```
and pi_context from
`def onPropertyInspectorDidAppear(self,obj:events_received_objs.PropertyInspectorDidAppear):`

but of course does not work -.-
any hint welcome :=)

**Comment by gri-gus** [comment]
@doabigcheese I promised to answer, but I'm still very busy.  I will try to find time tomorrow and answer the previous question and the current one.  There is a solution in both cases.
For your new question, start with the example provided in the README.  According to it, you will understand how to correctly send data through the sdk.
And here is the method you are looking for, it is in the `Action` class: 

```python
def on_property_inspector_did_appear(self, obj: events_received_objs.PropertyInspectorDidAppear) -> None:
    pass
``` 

But this is not the best option.  It is better to save the data you need in the settings, and then get it in html.  Moreover, js sdk has a callback for this.

**Comment by doabigcheese** [comment]
hm, so when starting the first trys like in your example it was working, but only from the action class, not from a threaded function...

**Comment by gri-gus** [comment]
Not relevant for new versions
