### ISSUE TITLE
SDK crashes when Streamdeck does not send all the colours

### ISSUE THREAD

**Issue by ROBOT0-VT** [gri-gus/streamdeck-python-sdk#8]
Pydantic validation fails when `InfoColors.disabledColor` and `InfoColors.mouseDownColor` are not sent by the streamdeck software. 

PR to follow

**Comment by gri-gus** [comment]
@ROBOT0-VT 
Describe under what conditions this happens. Please write your StreamDeck version, operating system, and which streamdeck device you are using.

**Comment by ROBOT0-VT** [comment]
Hiya! Sorry for being so brief with the issue, was investigating the issue just before I fell asleep 😂 

Log file:
[sample.log](https://github.com/gri-gus/streamdeck-python-sdk/files/14761160/sample.log)

OS: Windows 11
StreamDeck version: 6.5.2 (19936)
Device: Stream Deck MK.2

**Comment by ROBOT0-VT** [comment]
To better describe the fix, setting a field as `Optional` does not automatically set its default value to `None`. Thus, I set a default `None` for those fields, allowing them to pass validation

**Comment by ROBOT0-VT** [comment]
Okay, it seems like this is an issue across the repo, I'm seeing similar for `keydown`, `keyup` etc

EDIT: It's from different behaviour in pydantic 2 😶‍🌫️ For some reason `pipenv` didn't properly lock the correct version.

Works fine with pydantic 1
